apiVersion: apps/v1
kind: Deployment
metadata:
  name: webshop-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: zela1998/webshop_ui
          ports:
            - containerPort: 5173
              protocol: TCP
