apiVersion: v1
kind: Service
metadata: 
  name: webshop-ui
  labels:
    app: ui
spec: 
  selector: 
    app: ui
  type: NodePort
  ports: 
    - name: ui
      port: 5173
      targetPort: 5173
      nodePort: 30080

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    db: db
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432